- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python3-train-jobs-horizon
      - openstack-python3-train-jobs
