- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - openstack-python36-jobs
    check:
      jobs:
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - horizon-openstack-tox-python3-django111
