- project:
    check:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
