- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-xena-jobs-horizon
      - openstack-python3-xena-jobs
